# Generated by Django 5.0.3 on 2026-04-18 19:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=60)),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='For Image/Diagram Identification round', null=True, upload_to='question_images/')),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(help_text='A, B, C or D', max_length=1)),
                ('explanation', models.TextField(blank=True, help_text='Shown after answer — great for learning moments')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('quiz_type', models.CharField(choices=[('qualifier', 'Level Qualifier'), ('daily', 'Daily Life Quiz'), ('final', 'Grand Finals')], max_length=20)),
                ('round_type', models.CharField(choices=[('general', 'General Biology Round'), ('department', 'CBG Department Trivia'), ('speed', 'Speed Round'), ('image', 'Image / Diagram Identification'), ('final_high', 'Final High Stakes Round'), ('standard', 'Standard')], default='standard', max_length=20)),
                ('level', models.CharField(blank=True, help_text='Set only for qualifier quizzes', max_length=10, null=True)),
                ('date', models.DateField(blank=True, help_text='Set for daily quizzes', null=True)),
                ('day_label', models.CharField(blank=True, help_text="E.g. 'Football Day ⚽' — shown on the quiz page", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('time_limit', models.IntegerField(default=30, help_text='Seconds per question')),
                ('total_questions', models.IntegerField(default=10)),
                ('points_correct', models.IntegerField(default=10)),
                ('points_wrong', models.IntegerField(default=0, help_text='Use negative value e.g. -5 for buzzer penalty')),
                ('speed_bonus_enabled', models.BooleanField(default=False, help_text='Enable for Speed Round')),
                ('speed_bonus_max', models.IntegerField(default=5, help_text='Max extra points for fastest answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, help_text='Optional team color for display e.g. #FF5733', max_length=20)),
                ('total_score', models.IntegerField(default=0, help_text='Updated live during finals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('100', '100L'), ('200', '200L'), ('300', '300L'), ('400', '400L')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('speed_bonus_total', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='main.guestplayer')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='main.participant')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='main.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField()),
                ('time_taken', models.IntegerField(default=0, help_text='Seconds taken to answer')),
                ('speed_bonus', models.IntegerField(default=0, help_text='Bonus points awarded for speed')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.quiz'),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('speed_bonus', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='main.guestplayer')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='main.participant')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='main.quiz')),
            ],
            options={
                'ordering': ['-score', '-speed_bonus'],
            },
        ),
        migrations.CreateModel(
            name='DailyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(unique=True)),
                ('title', models.CharField(help_text="E.g. 'Football Day'", max_length=100)),
                ('emoji', models.CharField(blank=True, help_text='E.g. ⚽', max_length=5)),
                ('event_date', models.DateField()),
                ('quiz', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_event', to='main.quiz')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_membership', to='main.participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.team')),
            ],
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('participant__isnull', False)), fields=('participant', 'quiz'), name='unique_participant_quiz'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'participant')},
        ),
    ]
