# Generated by Django 5.0.3 on 2026-04-19 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_quizzes', to='main.question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_live_mode',
            field=models.BooleanField(default=False, help_text='Enable Host-controlled Live Stage mode'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='live_status',
            field=models.CharField(choices=[('waiting', 'Waiting to Start'), ('question_active', 'Question Active (Accepting Answers)'), ('answer_revealed', 'Answer Revealed'), ('leaderboard', 'Showing Leaderboard'), ('finished', 'Quiz Finished')], default='waiting', max_length=20),
        ),
    ]
