# Generated by Django 5.0.3 on 2026-04-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quiz_current_question_quiz_is_live_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='current_question_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
