# Generated by Django 5.0.3 on 2026-04-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_quiz_current_question_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='level',
            field=models.CharField(choices=[('100', '100L'), ('200', '200L'), ('300', '300L'), ('400', '400L')], max_length=30),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='level',
            field=models.CharField(blank=True, help_text='Set only for qualifier quizzes', max_length=30, null=True),
        ),
    ]
